### ISSUE TITLE
Rummy east

### ISSUE THREAD

**Issue by Vnschauhan** [Vnschauhan/Vans#1]
VER: 2.15.0(24030663)
PERMISSION: APP
ABI: arm64-v8a
MODEL: CPH2401
SDK: 33
RELEASE: 13
TARGET_SDK: 30
---StackTrace---
java.io.IOException: Archive is not a ZIP archive
	at l..<init>(X5YG:461)
	at l..<init>(X5YG:114)
	at l.ۘۡۥ.۠(2AQ4:82)
	at l..ۨ(D4W8:115)
	at l.ۖ۟ۖ.run(7ATF:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Vnschauhan** [comment]
VER: 2.15.0(24030663)
PERMISSION: APP
ABI: arm64-v8a
MODEL: CPH2401
SDK: 33
RELEASE: 13
TARGET_SDK: 30
---StackTrace---
java.io.IOException: Archive is not a ZIP archive
	at l.ۨ۟ۗۨ.<init>(X5YG:461)
	at l.ۨ۟ۗۨ.<init>(X5YG:114)
	at l.ۘۡۥ.۠(2AQ4:82)
	at l.ۘ۟ۘۨ.ۨ(D4W8:115)
	at l.ۖ۟ۖ.run(7ATF:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by Vnschauhan** [comment]
VER: 2.15.0(24030663)
PERMISSION: APP
ABI: arm64-v8a
MODEL: CPH2401
SDK: 33
RELEASE: 13
TARGET_SDK: 30
---StackTrace---
java.io.IOException: Archive is not a ZIP archive
	at l.ۨ۟ۗۨ.<init>(X5YG:461)
	at l.ۨ۟ۗۨ.<init>(X5YG:114)
	at l.ۘۡۥ.۠(2AQ4:82)
	at l.ۘ۟ۘۨ.ۨ(D4W8:115)
	at l.ۖ۟ۖ.run(7ATF:18)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
